"""
plot_detection_rate_grid.py
---------------------------
Plots colour-coded n_frames x frame_gap grids from the seq_eval_results sweep.

Always produces:
  detection_rate_grid.png  -- detection rate (% and fraction) from sequence_summary.json

If classifier_metrics.json is also present in each run directory (generated by
classifier_eval_mobilenet_sweep.sh), additionally produces:
  fpr_grid.png             -- false positive rate
  accuracy_grid.png        -- accuracy

Usage
-----
    python plot_detection_rate_grid.py

    # Point at a different results directory:
    python plot_detection_rate_grid.py --eval_dir seq_eval_results

    # Save to a custom output directory:
    python plot_detection_rate_grid.py --out_dir my_plots
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------

def load_results(eval_dir: Path) -> list[dict]:
    rows = []
    for summary_file in sorted(eval_dir.glob("mobilenet_*/sequence_summary.json")):
        run_dir  = summary_file.parent
        run_name = run_dir.name  # e.g. mobilenet_nf2_gap1
        try:
            parts = run_name.split("_")    # ['mobilenet', 'nf2', 'gap1']
            nf  = int(parts[1].replace("nf",  ""))
            gap = int(parts[2].replace("gap", ""))
        except (IndexError, ValueError):
            continue

        with open(summary_file) as f:
            summary = json.load(f)

        mob   = summary.get("pipelines", {}).get("mobilenet", {})
        n_seq = mob.get("n_sequences", 0)
        n_det = mob.get("n_detected",  0)
        rate  = mob.get("detection_rate", float("nan"))

        row = {"n_frames": nf, "gap": gap,
               "n_seq": n_seq, "n_det": n_det, "rate": rate,
               "fpr": float("nan"), "accuracy": float("nan"),
               "fp": None, "tn": None, "tp": None, "fn": None,
               "n_no_smoke": None}

        # Augment with FPR / Accuracy from classifier_metrics.json if present
        metrics_file = run_dir / "classifier_metrics.json"
        if metrics_file.exists():
            with open(metrics_file) as f:
                metrics = json.load(f)
            m = metrics.get("pipelines", {}).get("mobilenet", {})
            row.update({
                "fpr":      m.get("fpr",      float("nan")),
                "accuracy": m.get("accuracy", float("nan")),
                "tp":  m.get("tp"),  "fn": m.get("fn"),
                "fp":  m.get("fp"),  "tn": m.get("tn"),
                "n_no_smoke": (m.get("fp", 0) + m.get("tn", 0)) or None,
            })

        rows.append(row)
    return rows


# ---------------------------------------------------------------------------
# Generic grid plotter
# ---------------------------------------------------------------------------

def plot_grid(
    rows: list[dict],
    value_key: str,
    out_path: Path,
    title: str,
    cmap: str,
    cbar_label: str,
    higher_is_better: bool,
    cell_text_fn,          # fn(row) -> (top_str, bottom_str)
) -> None:
    valid = [r for r in rows if not np.isnan(r.get(value_key, float("nan")))]
    if not valid:
        print(f"No data for {value_key}, skipping {out_path.name}")
        return

    all_nf   = sorted({r["n_frames"] for r in valid})
    all_gaps = sorted({r["gap"]      for r in valid})
    lookup   = {(r["n_frames"], r["gap"]): r for r in valid}

    n_rows, n_cols = len(all_nf), len(all_gaps)
    grid = np.full((n_rows, n_cols), np.nan)
    for r in valid:
        i = all_nf.index(r["n_frames"])
        j = all_gaps.index(r["gap"])
        grid[i, j] = r[value_key]

    fig, ax = plt.subplots(figsize=(max(5, n_cols * 2.2), max(3.5, n_rows * 1.8)))

    vmin = np.nanmin(grid)
    vmax = np.nanmax(grid)
    im = ax.imshow(grid, cmap=cmap, vmin=vmin, vmax=vmax, aspect="auto")
    cbar = plt.colorbar(im, ax=ax, fraction=0.03, pad=0.04)
    cbar.set_label(cbar_label, fontsize=10)
    cbar.ax.yaxis.set_major_formatter(
        matplotlib.ticker.FuncFormatter(lambda x, _: f"{x:.0%}")
    )

    for i, nf in enumerate(all_nf):
        for j, gap in enumerate(all_gaps):
            r = lookup.get((nf, gap))
            if r is None:
                continue
            val = r[value_key]
            top_str, bot_str = cell_text_fn(r)
            norm_val = (val - vmin) / max(vmax - vmin, 1e-9)
            txt_color = "white" if norm_val > 0.75 else "black"
            ax.text(j, i - 0.1, top_str,
                    ha="center", va="center", fontsize=12, fontweight="bold",
                    color=txt_color)
            ax.text(j, i + 0.22, bot_str,
                    ha="center", va="center", fontsize=9, color=txt_color)

    # Highlight best cell
    best = np.unravel_index(
        np.nanargmax(grid) if higher_is_better else np.nanargmin(grid),
        grid.shape,
    )
    ax.add_patch(plt.Rectangle(
        (best[1] - 0.5, best[0] - 0.5), 1, 1,
        fill=False, edgecolor="royalblue", linewidth=2.5, label="Best",
    ))
    ax.legend(loc="upper left", fontsize=9, framealpha=0.8)

    ax.set_xticks(range(n_cols))
    ax.set_xticklabels([f"gap={g}" for g in all_gaps], fontsize=11)
    ax.set_yticks(range(n_rows))
    ax.set_yticklabels([f"nf={n}" for n in all_nf], fontsize=11)
    ax.set_xlabel("frame_gap", fontsize=12)
    ax.set_ylabel("n_frames",  fontsize=12)
    ax.set_title(title, fontsize=13, fontweight="bold")

    plt.tight_layout()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    plt.savefig(out_path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"Saved: {out_path}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--eval_dir", default="seq_eval_results",
                        help="Directory with mobilenet_nfN_gapM/ subdirs (default: seq_eval_results)")
    parser.add_argument("--out_dir", default=None,
                        help="Output directory (default: <eval_dir>/plots)")
    args = parser.parse_args()

    eval_dir = Path(args.eval_dir)
    if not eval_dir.is_dir():
        print(f"Directory not found: {eval_dir}")
        return

    out_dir = Path(args.out_dir) if args.out_dir else eval_dir / "plots"
    rows = load_results(eval_dir)
    print(f"Loaded {len(rows)} runs from {eval_dir.resolve()}")

    has_classifier = any(not np.isnan(r["fpr"]) for r in rows)
    if not has_classifier:
        print("No classifier_metrics.json found — only detection rate plot will be generated.")
        print("Run classifier_eval_mobilenet_sweep.sh to add FPR and Accuracy grids.")

    # Detection rate
    plot_grid(
        rows, "rate",
        out_dir / "detection_rate_grid.png",
        title="Smoke-sequence Detection Rate\n(% detected  |  detected / total sequences)",
        cmap="YlGn",
        cbar_label="Detection Rate",
        higher_is_better=True,
        cell_text_fn=lambda r: (f"{r['rate']:.1%}", f"{r['n_det']}/{r['n_seq']}"),
    )

    if has_classifier:
        # FPR
        plot_grid(
            rows, "fpr",
            out_dir / "fpr_grid.png",
            title="False Positive Rate (sequence-level)\n(% triggered  |  triggered / total no-smoke sequences)",
            cmap="YlOrRd",
            cbar_label="FPR  (lower is better)",
            higher_is_better=False,
            cell_text_fn=lambda r: (
                f"{r['fpr']:.1%}",
                f"{r['fp']}/{r['n_no_smoke']}" if r['fp'] is not None else "",
            ),
        )

        # Accuracy
        plot_grid(
            rows, "accuracy",
            out_dir / "accuracy_grid.png",
            title="Accuracy (sequence-level)\n(% correct  |  (TP+TN) / total sequences)",
            cmap="YlGn",
            cbar_label="Accuracy",
            higher_is_better=True,
            cell_text_fn=lambda r: (
                f"{r['accuracy']:.1%}",
                f"{(r['tp'] or 0) + (r['tn'] or 0)}/{(r['tp'] or 0) + (r['tn'] or 0) + (r['fp'] or 0) + (r['fn'] or 0)}",
            ),
        )


if __name__ == "__main__":
    main()
